package defaults

import (
	"reflect"
	"runtime"
)

// Setter is an interface for setting default values.
//
// Set calls SetDefaults on a struct once it has filled the struct's fields. A SetDefaults the struct
// has only by promotion from an embedded field is not called on the struct: it belongs to the field,
// which gets whatever call it would get as a named field.
type Setter interface {
	SetDefaults()
}

func callSetter(v interface{}) {
	if ds, ok := v.(Setter); ok {
		ds.SetDefaults()
	}
}

// hasPromotedSetter reports whether the SetDefaults of t, a struct type whose pointer implements
// Setter, is promoted from an embedded field rather than declared by t itself.
//
// reflect lists the two alike, under the same name and signature in the same method set, so this
// asks where the method's code comes from instead. For a promoted method the compiler generates a
// wrapper that calls through to the field, and positions it in "<autogenerated>"; a declared method
// is positioned in the file that declares it.
//
// The value's method set is read before the pointer's, because a method declared on a value receiver
// is in the pointer's set too, as exactly such a generated wrapper.
func hasPromotedSetter(t reflect.Type) bool {
	m, ok := t.MethodByName("SetDefaults")
	if !ok {
		m, _ = reflect.PointerTo(t).MethodByName("SetDefaults")
	}

	pc := m.Func.Pointer()
	file, _ := runtime.FuncForPC(pc).FileLine(pc)
	return file == "<autogenerated>"
}
